/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIngestionRouteImport } from './routes/admin/ingestion'
import { Route as EventosIdRouteImport } from './routes/eventos/$id'
import { Route as FilmesIdRouteImport } from './routes/filmes/$id'
import { Route as ApiPublicIngestCinematecaRouteImport } from './routes/api/public/ingest/cinemateca'
import { Route as ApiAdminIngestSourceSourceKeyRouteImport } from './routes/api/admin/ingest/source.$sourceKey'
import { Route as ApiInternalIngestSourceSourceKeyRouteImport } from './routes/api/internal/ingest/source.$sourceKey'
import { Route as ApiPublicIngestSourceSourceKeyRouteImport } from './routes/api/public/ingest/source.$sourceKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesIdRoute = FilmesIdRouteImport.update({
  id: '/filmes/$id',
  path: '/filmes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCinematecaRoute =
  ApiPublicIngestCinematecaRouteImport.update({
    id: '/api/public/ingest/cinemateca',
    path: '/api/public/ingest/cinemateca',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminIngestSourceSourceKeyRoute =
  ApiAdminIngestSourceSourceKeyRouteImport.update({
    id: '/api/admin/ingest/source/$sourceKey',
    path: '/api/admin/ingest/source/$sourceKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalIngestSourceSourceKeyRoute =
  ApiInternalIngestSourceSourceKeyRouteImport.update({
    id: '/api/internal/ingest/source/$sourceKey',
    path: '/api/internal/ingest/source/$sourceKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestSourceSourceKeyRoute =
  ApiPublicIngestSourceSourceKeyRouteImport.update({
    id: '/api/public/ingest/source/$sourceKey',
    path: '/api/public/ingest/source/$sourceKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$id': typeof FilmesIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/admin/ingest/source/$sourceKey': typeof ApiAdminIngestSourceSourceKeyRoute
  '/api/internal/ingest/source/$sourceKey': typeof ApiInternalIngestSourceSourceKeyRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$id': typeof FilmesIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/admin/ingest/source/$sourceKey': typeof ApiAdminIngestSourceSourceKeyRoute
  '/api/internal/ingest/source/$sourceKey': typeof ApiInternalIngestSourceSourceKeyRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/eventos/$id': typeof EventosIdRoute
  '/filmes/$id': typeof FilmesIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/admin/ingest/source/$sourceKey': typeof ApiAdminIngestSourceSourceKeyRoute
  '/api/internal/ingest/source/$sourceKey': typeof ApiInternalIngestSourceSourceKeyRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorar'
    | '/login'
    | '/admin/ingestion'
    | '/eventos/$id'
    | '/filmes/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/admin/ingest/source/$sourceKey'
    | '/api/internal/ingest/source/$sourceKey'
    | '/api/public/ingest/source/$sourceKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorar'
    | '/login'
    | '/admin/ingestion'
    | '/eventos/$id'
    | '/filmes/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/admin/ingest/source/$sourceKey'
    | '/api/internal/ingest/source/$sourceKey'
    | '/api/public/ingest/source/$sourceKey'
  id:
    | '__root__'
    | '/'
    | '/explorar'
    | '/login'
    | '/admin/ingestion'
    | '/eventos/$id'
    | '/filmes/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/admin/ingest/source/$sourceKey'
    | '/api/internal/ingest/source/$sourceKey'
    | '/api/public/ingest/source/$sourceKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  EventosIdRoute: typeof EventosIdRoute
  FilmesIdRoute: typeof FilmesIdRoute
  ApiPublicIngestCinematecaRoute: typeof ApiPublicIngestCinematecaRoute
  ApiAdminIngestSourceSourceKeyRoute: typeof ApiAdminIngestSourceSourceKeyRoute
  ApiInternalIngestSourceSourceKeyRoute: typeof ApiInternalIngestSourceSourceKeyRoute
  ApiPublicIngestSourceSourceKeyRoute: typeof ApiPublicIngestSourceSourceKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/$id': {
      id: '/filmes/$id'
      path: '/filmes/$id'
      fullPath: '/filmes/$id'
      preLoaderRoute: typeof FilmesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/cinemateca': {
      id: '/api/public/ingest/cinemateca'
      path: '/api/public/ingest/cinemateca'
      fullPath: '/api/public/ingest/cinemateca'
      preLoaderRoute: typeof ApiPublicIngestCinematecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingest/source/$sourceKey': {
      id: '/api/admin/ingest/source/$sourceKey'
      path: '/api/admin/ingest/source/$sourceKey'
      fullPath: '/api/admin/ingest/source/$sourceKey'
      preLoaderRoute: typeof ApiAdminIngestSourceSourceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/ingest/source/$sourceKey': {
      id: '/api/internal/ingest/source/$sourceKey'
      path: '/api/internal/ingest/source/$sourceKey'
      fullPath: '/api/internal/ingest/source/$sourceKey'
      preLoaderRoute: typeof ApiInternalIngestSourceSourceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/source/$sourceKey': {
      id: '/api/public/ingest/source/$sourceKey'
      path: '/api/public/ingest/source/$sourceKey'
      fullPath: '/api/public/ingest/source/$sourceKey'
      preLoaderRoute: typeof ApiPublicIngestSourceSourceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  EventosIdRoute: EventosIdRoute,
  FilmesIdRoute: FilmesIdRoute,
  ApiPublicIngestCinematecaRoute: ApiPublicIngestCinematecaRoute,
  ApiAdminIngestSourceSourceKeyRoute: ApiAdminIngestSourceSourceKeyRoute,
  ApiInternalIngestSourceSourceKeyRoute: ApiInternalIngestSourceSourceKeyRoute,
  ApiPublicIngestSourceSourceKeyRoute: ApiPublicIngestSourceSourceKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
