/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as FilmesIdRouteImport } from './routes/filmes/$id'
import { Route as EventosIdRouteImport } from './routes/eventos/$id'
import { Route as ApiPublicIngestCinematecaRouteImport } from './routes/api/public/ingest/cinemateca'
import { Route as ApiPublicIngestSourceSourceKeyRouteImport } from './routes/api/public/ingest/source.$sourceKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesIdRoute = FilmesIdRouteImport.update({
  id: '/filmes/$id',
  path: '/filmes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCinematecaRoute =
  ApiPublicIngestCinematecaRouteImport.update({
    id: '/api/public/ingest/cinemateca',
    path: '/api/public/ingest/cinemateca',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestSourceSourceKeyRoute =
  ApiPublicIngestSourceSourceKeyRouteImport.update({
    id: '/api/public/ingest/source/$sourceKey',
    path: '/api/public/ingest/source/$sourceKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/explorar': typeof ExplorarRoute
  '/filmes/$id': typeof FilmesIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/explorar': typeof ExplorarRoute
  '/eventos/$id': typeof EventosIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/explorar': typeof ExplorarRoute
  '/eventos/$id': typeof EventosIdRoute
  '/api/public/ingest/cinemateca': typeof ApiPublicIngestCinematecaRoute
  '/api/public/ingest/source/$sourceKey': typeof ApiPublicIngestSourceSourceKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/explorar'
    | '/filmes/$id'
    | '/eventos/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/public/ingest/source/$sourceKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eventos/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/public/ingest/source/$sourceKey'
  id:
    | '__root__'
    | '/'
    | '/eventos/$id'
    | '/api/public/ingest/cinemateca'
    | '/api/public/ingest/source/$sourceKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ExplorarRoute: typeof ExplorarRoute
  FilmesIdRoute: typeof FilmesIdRoute
  ApiPublicIngestCinematecaRoute: typeof ApiPublicIngestCinematecaRoute
  ApiPublicIngestSourceSourceKeyRoute: typeof ApiPublicIngestSourceSourceKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
      '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes/$id': {
      id: '/filmes/$id'
      path: '/filmes/$id'
      fullPath: '/filmes/$id'
      preLoaderRoute: typeof FilmesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/cinemateca': {
      id: '/api/public/ingest/cinemateca'
      path: '/api/public/ingest/cinemateca'
      fullPath: '/api/public/ingest/cinemateca'
      preLoaderRoute: typeof ApiPublicIngestCinematecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/source/$sourceKey': {
      id: '/api/public/ingest/source/$sourceKey'
      path: '/api/public/ingest/source/$sourceKey'
      fullPath: '/api/public/ingest/source/$sourceKey'
      preLoaderRoute: typeof ApiPublicIngestSourceSourceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ExplorarRoute: ExplorarRoute,
  FilmesIdRoute: FilmesIdRoute,
  EventosIdRoute: EventosIdRoute,
  ApiPublicIngestCinematecaRoute: ApiPublicIngestCinematecaRoute,
  ApiPublicIngestSourceSourceKeyRoute: ApiPublicIngestSourceSourceKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
